def distinct_powers(limit_a, limit_b):
    """
    Calculate the number of distinct terms generated by a^b
    for 2 <= a <= limit_a and 2 <= b <= limit_b.
    """
    terms = set()

    for a in range(2, limit_a + 1):
        for b in range(2, limit_b + 1):
            terms.add(a ** b)

    return len(terms)

# Set the limits
limit_a = 100
limit_b = 100

# Calculate the number of distinct terms
result = distinct_powers(limit_a, limit_b)
print(f"The number of distinct terms generated by a^b for 2 <= a <= {limit_a} and 2 <= b <= {limit_b} is {result}.")
